In [12]:
import pandas as pd
df=pd.read_csv('listings.csv')
df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2318,Casa Madrona - Urban Oasis 1 block from the park!,2536,Megan,Central Area,Madrona,47.61094,-122.29286,Entire home/apt,475,30,32,2020-02-01,0.58,2,238
1,6606,"Fab, private seattle urban cottage!",14942,Joyce,Other neighborhoods,Wallingford,47.65444,-122.33629,Entire home/apt,102,2,153,2021-07-12,2.45,1,87
2,9419,Glorious sun room w/ memory foambed,30559,Angielena,Other neighborhoods,Georgetown,47.55017,-122.31937,Private room,75,2,149,2021-06-28,1.12,9,275
3,9531,The Adorable Sweet Orange Craftsman,31481,Cassie,West Seattle,Fairmount Park,47.55495,-122.38663,Entire home/apt,165,5,45,2021-05-31,0.52,2,276
4,9534,The Coolest Tangerine Dream MIL!,31481,Cassie,West Seattle,Fairmount Park,47.55627,-122.38607,Entire home/apt,125,5,58,2021-04-25,0.58,2,311

In [13]:
df.tail()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
4091,50998875,Authentic Brick Condo - Great Wifi & little ex...,383863361,Brady,Downtown,First Hill,47.608750,-122.325930,Entire home/apt,315,30,0,NaN,NaN,7,184
4092,51010345,"Bright First Hill 1BR w/ Gym, Lounge, Roof, 90...",107434423,Blueground,Central Area,Minor,47.608200,-122.311951,Entire home/apt,318,30,0,NaN,NaN,128,365
4093,51023498,Well-kept apartment home | 2BR in Seattle,359069961,Kia,Cascade,South Lake Union,47.623880,-122.334250,Entire home/apt,235,30,0,NaN,NaN,59,365
4094,51023636,"Cozy Crash Pad! (Yard, Parking, DT Access via ...",68726541,Barron,Beacon Hill,Mid-Beacon Hill,47.549706,-122.305275,Private room,84,1,0,NaN,NaN,2,41
4095,51033528,Great Apartment home | 2 BR in Seattle,368944610,Carolyn,University District,University District,47.660532,-122.320648,Entire home/apt,222,31,0,NaN,NaN,26,357

In [14]:
df.drop(['name','host_id'],axis=1, inplace=True)

In [15]:
df.head()

,id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2318,Megan,Central Area,Madrona,47.61094,-122.29286,Entire home/apt,475,30,32,2020-02-01,0.58,2,238
1,6606,Joyce,Other neighborhoods,Wallingford,47.65444,-122.33629,Entire home/apt,102,2,153,2021-07-12,2.45,1,87
2,9419,Angielena,Other neighborhoods,Georgetown,47.55017,-122.31937,Private room,75,2,149,2021-06-28,1.12,9,275
3,9531,Cassie,West Seattle,Fairmount Park,47.55495,-122.38663,Entire home/apt,165,5,45,2021-05-31,0.52,2,276
4,9534,Cassie,West Seattle,Fairmount Park,47.55627,-122.38607,Entire home/apt,125,5,58,2021-04-25,0.58,2,311

In [24]:
df1=df.set_index('id', drop=True, append=False, inplace=False, verify_integrity=False)

In [25]:
df1[0:3]

,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
id,,,,,,,,,,,,,
2318,Megan,Central Area,Madrona,47.61094,-122.29286,Entire home/apt,475,30,32,2020-02-01,0.58,2,238
6606,Joyce,Other neighborhoods,Wallingford,47.65444,-122.33629,Entire home/apt,102,2,153,2021-07-12,2.45,1,87
9419,Angielena,Other neighborhoods,Georgetown,47.55017,-122.31937,Private room,75,2,149,2021-06-28,1.12,9,275

In [28]:
df2=df1.rename(columns={'last_review':'Date_Of_Review'}, inplace=False)
df2.head()

,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,Date_Of_Review,reviews_per_month,calculated_host_listings_count,availability_365
id,,,,,,,,,,,,,
2318,Megan,Central Area,Madrona,47.61094,-122.29286,Entire home/apt,475,30,32,2020-02-01,0.58,2,238
6606,Joyce,Other neighborhoods,Wallingford,47.65444,-122.33629,Entire home/apt,102,2,153,2021-07-12,2.45,1,87
9419,Angielena,Other neighborhoods,Georgetown,47.55017,-122.31937,Private room,75,2,149,2021-06-28,1.12,9,275
9531,Cassie,West Seattle,Fairmount Park,47.55495,-122.38663,Entire home/apt,165,5,45,2021-05-31,0.52,2,276
9534,Cassie,West Seattle,Fairmount Park,47.55627,-122.38607,Entire home/apt,125,5,58,2021-04-25,0.58,2,311